#!/bin/bash
version=$(cat ./VERSION)
script_name=`basename "$0"`
if test "$1" = "-h"; then
    echo ""
    echo "xcbasic64 $version"
    echo "This script compiles an XC-BASIC source to binary executable."
    echo ""
    echo "USAGE:"
    echo "$script_name infile.bas outfile.prg"
    echo ""
    exit
fi
MACHINE_TYPE=`uname -m`
if [ ${MACHINE_TYPE} == 'x86_64' ]; then
  bindir="linux_x86_64"
else
  bindir="linux_x86"
fi
bin/$bindir/xcbasic64 "$1" > /tmp/xcbtmp.asm && third_party/dasm-2.20.11/dasm.Linux.x86 /tmp/xcbtmp.asm -o"$2"
rm /tmp/xcbtmp.asm