#!/bin/bash
version=$(cat ./VERSION)
script_name=`basename "$0"`
if test "$1" = "-h"; then
    echo ""
    echo "xcbasic64 $version"
    echo "This script compiles an XC-BASIC source to binary executable."
    echo ""
    echo "USAGE:"
    echo "$script_name infile.bas outfile.prg"
    echo ""
    exit
fi
bin/macos_x86_64/xcbasic64 "$1" > /tmp/xcbtmp.asm && third_party/dasm-2.20.11/dasm.OSX.x86_64 /tmp/xcbtmp.asm -o"$2"
rm /tmp/xcbtmp.asm